# Site settings
name: 这是啥
email: wanggang.sdu@gmail.com
author: witmusk
url: https://witmusk.github.io/
resume_site: ""
github: https://github.com/witmusk/
baseurl: ""
description: 这到底是啥!
meta_description: spring;spring-boot;架构之路;消息;缓存
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: witmusk

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

